"""End-to-end integration test for the autonomous discover pipeline.

Tests the full Pipeline().discover() flow with mocked LLM backend,
ensuring simulation generation, validation, sweeps, and reporting
all work together correctly.
"""
from __future__ import annotations

import json
from unittest.mock import MagicMock

from simulating_anything.campaign.manager import CampaignManager
from simulating_anything.pipeline import Pipeline
from simulating_anything.types.campaign import CampaignReport

# Valid simulation code that the mock LLM will "generate"
_OSCILLATOR_SIM_CODE = '''
class GeneratedOscillator(SimulationEnvironment):
    """Simple harmonic oscillator generated by LLM."""

    def __init__(self, config):
        super().__init__(config)
        p = config.parameters
        self.k = p.get("k", 1.0)
        self.m = p.get("m", 1.0)

    def reset(self, seed=None):
        self._state = np.array([1.0, 0.0])
        self._step_count = 0
        return self._state

    def step(self):
        dt = self.config.dt
        x, v = self._state
        a = -self.k / self.m * x
        self._state = np.array([x + v * dt, v + a * dt])
        self._step_count += 1
        return self._state

    def observe(self):
        return self._state
'''

_PLAN_JSON = json.dumps({
    "sub_questions": ["What governs the oscillation frequency?"],
    "experiments": [
        {
            "id": "exp_1",
            "description": "Test spring-mass oscillation dynamics",
            "simulation_description": "Simple harmonic oscillator with spring constant k and mass m",
            "parameters_to_sweep": {"k": [0.5, 5.0]},
            "target_observables": ["position", "velocity"],
            "expected_outcome": "omega = sqrt(k/m)",
            "depends_on": [],
        }
    ],
    "success_criteria": ["Find frequency-stiffness relationship"],
})

_REPLAN_JSON = json.dumps({
    "new_experiments": [],
    "completed": True,
    "reasoning": "Found the expected relationship",
})


class TestDiscoverPipeline:
    """Integration tests for Pipeline.discover() and CampaignManager."""

    def test_campaign_manager_full_flow(self, tmp_path):
        """Test CampaignManager with mocked LLM produces valid report."""
        mock_backend = MagicMock()
        mock_backend.ask.side_effect = [
            _PLAN_JSON,
            _OSCILLATOR_SIM_CODE,
            _REPLAN_JSON,
        ]

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=5,
            n_sweep_points=5,
            n_sim_steps=20,
        )

        report = cm.run_campaign("What determines oscillation frequency?")

        assert isinstance(report, CampaignReport)
        assert report.question == "What determines oscillation frequency?"
        assert report.experiments_run >= 0
        assert isinstance(report.conclusion, str)
        assert report.research_notebook_md is not None

    def test_campaign_manager_no_backend(self, tmp_path):
        """CampaignManager without LLM uses fallback plan, then fails gracefully."""
        cm = CampaignManager(
            backend=None,
            output_dir=str(tmp_path),
            max_steps=3,
            n_sweep_points=5,
            n_sim_steps=10,
        )

        report = cm.run_campaign("Test question", max_steps=3)

        assert isinstance(report, CampaignReport)
        assert report.question == "Test question"
        # Should handle gracefully without crashing
        assert isinstance(report.conclusion, str)

    def test_campaign_saves_artifacts(self, tmp_path):
        """Campaign saves report JSON and notebook markdown."""
        mock_backend = MagicMock()
        mock_backend.ask.side_effect = [
            _PLAN_JSON,
            _OSCILLATOR_SIM_CODE,
            _REPLAN_JSON,
        ]

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=5,
            n_sweep_points=5,
            n_sim_steps=20,
        )

        report = cm.run_campaign("Oscillation frequency test")

        # Check artifacts saved
        campaign_dir = tmp_path / "Oscillation_frequency_test"  # re.sub(r'[^\w\-]', '_', ...)
        assert campaign_dir.exists()
        assert (campaign_dir / "campaign_report.json").exists()
        assert (campaign_dir / "research_notebook.md").exists()

        # Verify report JSON is valid
        report_json = json.loads((campaign_dir / "campaign_report.json").read_text())
        assert report_json["question"] == "Oscillation frequency test"

    def test_campaign_stagnation_stops(self, tmp_path):
        """Campaign stops after 3 steps with no new findings."""
        mock_backend = MagicMock()

        # Plan with experiment, but sim code that produces no sweep-able data
        minimal_plan = json.dumps({
            "sub_questions": ["Q1"],
            "experiments": [
                {
                    "id": f"exp_{i}",
                    "description": f"Experiment {i}",
                    "simulation_description": f"Test sim {i}",
                    "parameters_to_sweep": {},
                    "target_observables": ["x"],
                    "expected_outcome": "linear",
                    "depends_on": [],
                }
                for i in range(5)
            ],
            "success_criteria": ["Find something"],
        })

        simple_sim = '''
class SimpleSim(SimulationEnvironment):
    def __init__(self, config):
        super().__init__(config)
    def reset(self, seed=None):
        self._state = np.array([1.0])
        self._step_count = 0
        return self._state
    def step(self):
        self._step_count += 1
        return self._state
    def observe(self):
        return self._state
'''

        mock_backend.ask.side_effect = [minimal_plan] + [simple_sim] * 10 + [
            json.dumps({"new_experiments": [], "completed": True, "reasoning": "Done"})
        ] * 5

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=10,
            n_sweep_points=5,
            n_sim_steps=10,
        )

        report = cm.run_campaign("Stagnation test")
        # Should stop before max_steps due to stagnation
        assert report.experiments_run <= 10

    def test_campaign_report_structure(self, tmp_path):
        """Verify CampaignReport has all expected fields."""
        mock_backend = MagicMock()
        mock_backend.ask.side_effect = [
            _PLAN_JSON,
            _OSCILLATOR_SIM_CODE,
            _REPLAN_JSON,
        ]

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=5,
            n_sweep_points=5,
            n_sim_steps=20,
        )

        report = cm.run_campaign("Structure test")

        assert hasattr(report, "question")
        assert hasattr(report, "plan")
        assert hasattr(report, "experiments_run")
        assert hasattr(report, "experiments_failed")
        assert hasattr(report, "discoveries")
        assert hasattr(report, "validated_discoveries")
        assert hasattr(report, "hypothesis_results")
        assert hasattr(report, "generated_simulations")
        assert hasattr(report, "notebook_entries")
        assert hasattr(report, "conclusion")
        assert hasattr(report, "research_notebook_md")

    def test_pipeline_discover_method_exists(self):
        """Pipeline has a discover() method."""
        pipeline = Pipeline()
        assert hasattr(pipeline, "discover")
        assert callable(pipeline.discover)

    def test_campaign_with_validation_failure(self, tmp_path):
        """Test that campaigns handle validation failures gracefully."""
        mock_backend = MagicMock()

        # Sim code that produces NaN
        bad_sim = '''
class BadSim(SimulationEnvironment):
    def __init__(self, config):
        super().__init__(config)
    def reset(self, seed=None):
        self._state = np.array([1.0])
        self._step_count = 0
        return self._state
    def step(self):
        self._state = np.array([float('nan')])
        self._step_count += 1
        return self._state
    def observe(self):
        return self._state
'''

        mock_backend.ask.side_effect = [
            _PLAN_JSON,
            bad_sim,
            json.dumps({"new_experiments": [], "completed": True, "reasoning": "Done"}),
        ]

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=3,
            n_sweep_points=3,
            n_sim_steps=10,
        )

        report = cm.run_campaign("Validation failure test")

        assert isinstance(report, CampaignReport)
        assert report.experiments_failed >= 1

    def test_campaign_with_sweep_parameters(self, tmp_path):
        """Test campaign correctly sweeps parameters."""
        mock_backend = MagicMock()
        mock_backend.ask.side_effect = [
            _PLAN_JSON,
            _OSCILLATOR_SIM_CODE,
            _REPLAN_JSON,
        ]

        cm = CampaignManager(
            backend=mock_backend,
            output_dir=str(tmp_path),
            max_steps=5,
            n_sweep_points=10,
            n_sim_steps=50,
        )

        report = cm.run_campaign("Sweep parameter test")
        assert isinstance(report, CampaignReport)
        # Should have at least attempted to run experiments
        assert report.experiments_run + report.experiments_failed >= 0
